### PR TITLE
fix parallel services problem

### PR DESCRIPTION
**Pull request by RomanIovlev**
Fix two services problem and add tests for service instances

### CODE REVIEW

**Review by epam-ocherniavskaia — APPROVED** [review]

**Comment by JDIReporter** [comment]
[1334] - xlL1izmGRu5k

**Comment by JDIReporter** [comment]
[1334] - 506iV55uLVLD

**Comment by JDIReporter** [comment]
[1334] - iuDNy4TE1Cta

**Comment by JDIReporter** [comment]
[1336] - B4iN6eme3Cb9

**Comment by JDIReporter** [comment]
[1336] - bQXd6yvbPHzF

**Comment by JDIReporter** [comment]
[1334] - Allure report on Netlify: https://5f4fddd2ab3cfa19f43e719c--jdi-dark.netlify.app

**Comment by JDIReporter** [comment]
[1336] - WuRvZQKt5BOq

**Comment by JDIReporter** [comment]
[1336] - Allure report on Netlify: https://5f4fdf6b3dac7922b60da2f8--jdi-dark.netlify.app

**Comment by JDIReporter** [comment]
[1338] - lv7yJWRWMgvJ

**Comment by JDIReporter** [comment]
[1338] - ramnpqYTzyo6

**Comment by JDIReporter** [comment]
[1338] - rz2muf3yhdcM

**Comment by JDIReporter** [comment]
[1340] - 1DORxaZ8ejSi

**Comment by JDIReporter** [comment]
[1340] - tbnZaFZIf2za

**Pull request merged**
