### PR TITLE
Correct Allure steps with logging aspect (AOP)

### PR DESCRIPTION
**Pull request by HronoSF**

### CODE REVIEW

**Comment by JDIReporter** [comment]
[692] - https://transfer.sh/YFyIs/jdi-dark-tests.tar.gz

**Comment by JDIReporter** [comment]
[692] - Allure report on Netlify: https://5e66819cc2b0733a5bde284b--jdi-dark.netlify.com

**Comment by JDIReporter** [comment]
[694] - https://transfer.sh/Ldt7s/jdi-dark-tests.tar.gz

**Comment by JDIReporter** [comment]
[694] - Allure report on Netlify: https://5e6682ac5ed6f70be4711bcd--jdi-dark.netlify.com

**Comment by JDIReporter** [comment]
[696] - https://transfer.sh/IsLiv/jdi-dark-tests.tar.gz

**Comment by JDIReporter** [comment]
[696] - Allure report on Netlify: https://5e66878b24627b422ab33050--jdi-dark.netlify.com

**Comment by JDIReporter** [comment]
[698] - https://transfer.sh/GEHRW/jdi-dark-tests.tar.gz

**Comment by JDIReporter** [comment]
[698] - Allure report on Netlify: https://5e668e87d8787a9edd2ee57f--jdi-dark.netlify.com

**Comment by BelAn97** [comment]
move to draft

**Pull request closed without merging**
