### PR TITLE
430 Update WithRetryService and fix 2 broken tests

### PR DESCRIPTION
**Pull request by AkioFaris**

### CODE REVIEW

**Comment by JDIReporter** [comment]
[1379] - 8Xze7KMYvqgt

**Comment by JDIReporter** [comment]
[1379] - mlC35Stj9YWX

**Comment by JDIReporter** [comment]
[1379] - q1tXFmyw5iC7

**Comment by AkioFaris** [comment]
Cancelled

**Comment by JDIReporter** [comment]
[1379] - Allure report on Netlify: https://5f5a2e02bca9f3289e116342--jdi-dark.netlify.app

**Comment by JDIReporter** [comment]
[1383] - 9e7QeaNR9CQV

**Comment by JDIReporter** [comment]
[1383] - 8FjeWdFl7pwm

**Comment by JDIReporter** [comment]
[1383] - k84D71Mf3UEo

**Comment by JDIReporter** [comment]
[1383] - Allure report on Netlify: https://5f5a3e4180d015014153d560--jdi-dark.netlify.app

**Comment by JDIReporter** [comment]
[1386] - bPLrYjxvyjY7

**Comment by JDIReporter** [comment]
[1386] - ha22g5dhP3Qa

**Comment by JDIReporter** [comment]
[1386] - orxiZC2aHa0t

**Comment by JDIReporter** [comment]
[1386] - Allure report on Netlify: https://5f5b573b0cbbf30b17ef52d7--jdi-dark.netlify.app

**Review by BelAn97 — APPROVED** [review]

**Pull request merged**
