### PR TITLE
Refactoring and improvements

### PR DESCRIPTION
**Pull request by splekhanov**
- got rid off unnecessary things (dependencies, annontations, etc);
- improved Optional type checks and exceptions throws
- changed manual roles handling to Spring Security mechanism
- switched native query in repository to HQL
- request mapping improvements

### CODE REVIEW

**Comment by JDIReporter** [comment]
[1447] - KLwzdY30C8uU

**Comment by JDIReporter** [comment]
[1447] - Ah0sw6JBDLMc

**Comment by JDIReporter** [comment]
[1447] - r2rfyYZgWkrK

**Comment by JDIReporter** [comment]
[1447] - Allure report on Netlify: https://5f7e1e25728cde104cdebc85--jdi-dark.netlify.app

**Review by romaha08 — APPROVED** [review]

**Pull request merged**
