### PR TITLE
rename The method name

### PR DESCRIPTION
**Pull request by tsvetaevAlex**
Rename method name 'NoFails' according [a-z][a-zA-Z0-9]

### CODE REVIEW

**Comment by JDIReporter** [comment]
[667] - Could not save metadata Could not save metadata Could not save metadata

**Comment by JDIReporter** [comment]
[667] - Allure report on Netlify: https://5e5f42856fee91435f38c5dc--jdi-dark.netlify.com

**Comment by tsvetaevAlex** [comment]
All checks have passed
This branch has no conflicts with the base branch

**Comment by tsvetaevAlex** [comment]
task done

**Pull request merged**
