### PR TITLE
45 error message test

### PR DESCRIPTION
**Pull request by VShutkina**
ErrorMessageTrelloTest class is added for error handling cases for TrelloAPI

### CODE REVIEW

**Comment by JDIReporter** [comment]
[36] - Could not save metadata Could not save metadata Could not save metadata

**Comment by JDIReporter** [comment]
[38] - Could not save metadata Could not save metadata Could not save metadata

**Comment by JDIReporter** [comment]
[37] - Could not save metadata Could not save metadata Could not save metadata

**Comment by JDIReporter** [comment]
[43] - Could not save metadata Could not save metadata Could not save metadata

**Comment by ElenaPoduzova** [comment]
Review has been done.

**Pull request merged**
