### PR TITLE
added path tests

### PR DESCRIPTION
**Pull request by hellokitties**
added path tests https://github.com/jdi-testing/jdi-dark/issues/52
fixed path tests runs when run several tests . https://github.com/jdi-testing/jdi-dark/issues/115

### CODE REVIEW

**Comment by JDIReporter** [comment]
[254] - https://transfer.sh/ChiT3/jdi-dark-bdd-tests.tar.gz

**Comment by JDIReporter** [comment]
[254] - https://transfer.sh/FOdTz/jdi-dark-tests.tar.gz

**Comment by JDIReporter** [comment]
[254] - Allure report on Netlify: https://5e3adb88b71e6744c4be74fa--jdi-dark.netlify.com

**Comment by hellokitties** [comment]
mistakenly made pr from wrong branch

**Pull request closed without merging**
