### PR TITLE
49 content type tests

### PR DESCRIPTION
**Pull request by maryvictol**

### CODE REVIEW

**Comment by JDIReporter** [comment]
[346] - Could not save metadata Could not save metadata Could not save metadata

**Comment by JDIReporter** [comment]
[346] - Allure report on Netlify: https://5e4289997ca1eeed8ee2c666--jdi-dark.netlify.com

**Comment by JDIReporter** [comment]
[356] - Could not save metadata Could not save metadata Could not save metadata

**Comment by JDIReporter** [comment]
[356] - Allure report on Netlify: https://5e43c44a21ab928deb148b44--jdi-dark.netlify.com

**Comment by JDIReporter** [comment]
[359] - Could not save metadata Could not save metadata Could not save metadata

**Comment by JDIReporter** [comment]
[359] - Allure report on Netlify: https://5e43c5ffc83e45abd7a28938--jdi-dark.netlify.com

**Comment by JDIReporter** [comment]
[367] - Could not save metadata Could not save metadata Could not save metadata

**Comment by JDIReporter** [comment]
[367] - Allure report on Netlify: https://5e43f20e94b3849a7ea676be--jdi-dark.netlify.com

**Comment by maryvictol** [comment]
> 
> 
> Need to resolve conflicts with master.

**Comment by JDIReporter** [comment]
[373] - https://transfer.sh/vQ7YZ/jdi-dark-tests.tar.gz

**Comment by JDIReporter** [comment]
[373] - Allure report on Netlify: https://5e43fbdfb47246c3c3528182--jdi-dark.netlify.com

**Pull request merged**
