### PR TITLE
426 Fix domain replacement (ServiceDomain settings improvements)

### PR DESCRIPTION
**Pull request by AkioFaris**
Fix domain replacement in replaceTemplateVariableInDomain()

### CODE REVIEW

**Comment by JDIReporter** [comment]
[1353] - ZDT6KZtriPVn

**Comment by JDIReporter** [comment]
[1353] - UGwYei2W2mUW

**Comment by JDIReporter** [comment]
[1353] - SCVVQupLRHai

**Comment by JDIReporter** [comment]
[1353] - Allure report on Netlify: https://5f50be2d1ec8690082e7d9de--jdi-dark.netlify.app

**Comment by JDIReporter** [comment]
[1355] - B6R2WQ6hFmWU

**Comment by JDIReporter** [comment]
[1355] - WFoMR8wE77xg

**Comment by JDIReporter** [comment]
[1355] - CDO1T6koAiPV

**Comment by JDIReporter** [comment]
[1355] - Allure report on Netlify: https://5f50bfab411555008507bf59--jdi-dark.netlify.app

**Review by BelAn97 — APPROVED** [review]

**Pull request merged**
